export const dummy_data = [
  {
    adult: false,
    backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    original_language: 'en',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview:
      'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    media_type: 'movie',
    genre_ids: [16, 28, 12],
    popularity: 2433.631,
    release_date: '2023-05-31',
    video: false,
    vote_average: 8.456,
    vote_count: 3736,
  },
  {
    adult: false,
    backdrop_path: '/jZIYaISP3GBSrVOPfrp98AMa8Ng.jpg',
    id: 976573,
    title: 'Elemental',
    original_language: 'en',
    original_title: 'Elemental',
    overview:
      'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
    poster_path: '/8riWcADI1ekEiBguVB9vkilhiQm.jpg',
    media_type: 'movie',
    genre_ids: [16, 35, 10751, 14, 10749],
    popularity: 3832.175,
    release_date: '2023-06-14',
    video: false,
    vote_average: 7.798,
    vote_count: 1382,
  },
  {
    adult: false,
    backdrop_path: '/sC8YOcp8tOQ5s9RgGsZnLDGTZSa.jpg',
    id: 724209,
    title: 'Heart of Stone',
    original_language: 'en',
    original_title: 'Heart of Stone',
    overview:
      'An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable — and dangerous — weapon.',
    poster_path: '/vB8o2p4ETnrfiWEgVxHmHWP9yRl.jpg',
    media_type: 'movie',
    genre_ids: [53, 28],
    popularity: 3796.765,
    release_date: '2023-08-09',
    video: false,
    vote_average: 6.971,
    vote_count: 749,
  },
  {
    adult: false,
    backdrop_path: '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    id: 872585,
    title: 'Oppenheimer',
    original_language: 'en',
    original_title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    media_type: 'movie',
    genre_ids: [18, 36],
    popularity: 675.182,
    release_date: '2023-07-19',
    video: false,
    vote_average: 8.267,
    vote_count: 2336,
  },
  {
    adult: false,
    backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
    id: 346698,
    title: 'Barbie',
    original_language: 'en',
    original_title: 'Barbie',
    overview:
      'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
    poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    media_type: 'movie',
    genre_ids: [35, 12, 14],
    popularity: 1456.526,
    release_date: '2023-07-19',
    video: false,
    vote_average: 7.423,
    vote_count: 3341,
  },
  {
    adult: false,
    backdrop_path: '/zN41DPmPhwmgJjHwezALdrdvD0h.jpg',
    id: 615656,
    title: 'Meg 2: The Trench',
    original_language: 'en',
    original_title: 'Meg 2: The Trench',
    overview:
      'An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.',
    poster_path: '/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg',
    media_type: 'movie',
    genre_ids: [28, 878, 27],
    popularity: 1183.525,
    release_date: '2023-08-02',
    video: false,
    vote_average: 6.9,
    vote_count: 580,
  },
  {
    adult: false,
    backdrop_path: '/rRcNmiH55Tz0ugUsDUGmj8Bsa4V.jpg',
    id: 884605,
    title: 'No Hard Feelings',
    original_language: 'en',
    original_title: 'No Hard Feelings',
    overview:
      'On the brink of losing her childhood home, Maddie discovers an intriguing job listing: wealthy helicopter parents looking for someone to “date” their introverted 19-year-old son, Percy, before he leaves for college. To her surprise, Maddie soon discovers the awkward Percy is no sure thing.',
    poster_path: '/4K7gQjD19CDEPd7A9KZwr2D9Nco.jpg',
    media_type: 'movie',
    genre_ids: [35, 10749],
    popularity: 1336.849,
    release_date: '2023-06-15',
    video: false,
    vote_average: 7.126,
    vote_count: 870,
  },
  {
    adult: false,
    backdrop_path: '/H6j5smdpRqP9a8UnhWp6zfl0SC.jpg',
    id: 565770,
    title: 'Blue Beetle',
    original_language: 'en',
    original_title: 'Blue Beetle',
    overview:
      'Recent college grad Jaime Reyes returns home full of aspirations for his future, only to find that home is not quite as he left it. As he searches to find his purpose in the world, fate intervenes when Jaime unexpectedly finds himself in possession of an ancient relic of alien biotechnology: the Scarab.',
    poster_path: '/lZ2sOCMCcGaPppaXj0Wiv0S7A08.jpg',
    media_type: 'movie',
    genre_ids: [28, 878],
    popularity: 519.115,
    release_date: '2023-08-16',
    video: false,
    vote_average: 6.976,
    vote_count: 228,
  },
  {
    adult: false,
    backdrop_path: '/jDjmnEuNUfWHg8rbW6u8mylkcO0.jpg',
    id: 832502,
    title: 'The Monkey King',
    original_language: 'en',
    original_title: 'The Monkey King',
    overview:
      'A stick-wielding monkey teams with a young girl on an epic quest for immortality, battling demons, dragons, gods — and his own ego — along the way.',
    poster_path: '/i6ye8ueFhVE5pXatgyRrZ83LBD8.jpg',
    media_type: 'movie',
    genre_ids: [16, 14, 12, 10751, 35],
    popularity: 279.653,
    release_date: '2023-08-11',
    video: false,
    vote_average: 6.841,
    vote_count: 69,
  },
  {
    adult: false,
    backdrop_path: '/yF1eOkaYvwiORauRCPWznV9xVvi.jpg',
    id: 298618,
    title: 'The Flash',
    original_language: 'en',
    original_title: 'The Flash',
    overview:
      "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
    poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 1405.843,
    release_date: '2023-06-13',
    video: false,
    vote_average: 6.964,
    vote_count: 2472,
  },
  {
    adult: false,
    backdrop_path: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    id: 447365,
    title: 'Guardians of the Galaxy Vol. 3',
    original_language: 'en',
    original_title: 'Guardians of the Galaxy Vol. 3',
    overview:
      'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
    poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    media_type: 'movie',
    genre_ids: [878, 12, 28],
    popularity: 773.535,
    release_date: '2023-05-03',
    video: false,
    vote_average: 8.037,
    vote_count: 4477,
  },
  {
    adult: false,
    backdrop_path: '/csz3oWxd04wgXUzenXgenIVwXGl.jpg',
    id: 930094,
    title: 'Red, White & Royal Blue',
    original_language: 'en',
    original_title: 'Red, White & Royal Blue',
    overview:
      "After an altercation between Alex, the president's son, and Britain's Prince Henry at a royal event becomes tabloid fodder, their long-running feud now threatens to drive a wedge in U.S./British relations. When the rivals are forced into a staged truce, their icy relationship begins to thaw and the friction between them sparks something deeper than they ever expected.",
    poster_path: '/vM1HzW1zA8QQ5Cw9g2tWdAxlbOQ.jpg',
    media_type: 'movie',
    genre_ids: [35, 10749],
    popularity: 394.122,
    release_date: '2023-07-27',
    video: false,
    vote_average: 8.308,
    vote_count: 601,
  },
  {
    adult: false,
    backdrop_path: '/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg',
    id: 385687,
    title: 'Fast X',
    original_language: 'en',
    original_title: 'Fast X',
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
    media_type: 'movie',
    genre_ids: [28, 80, 53],
    popularity: 1087.188,
    release_date: '2023-05-17',
    video: false,
    vote_average: 7.3,
    vote_count: 3462,
  },
  {
    adult: false,
    backdrop_path: '/WyGsyzSwGN4ZY9ZG2SJzGM4UPe.jpg',
    id: 885331,
    title: 'Gadar 2',
    original_language: 'hi',
    original_title: 'गदर २',
    overview:
      'During the Indo-Pakistani War of 1971, Tara Singh returns to Pakistan to bring his son, Charanjeet, back home.',
    poster_path: '/ipoUI3FzVTczg2r8mYxNlE5SsMh.jpg',
    media_type: 'movie',
    genre_ids: [28, 18, 53],
    popularity: 52.644,
    release_date: '2023-08-11',
    video: false,
    vote_average: 7.192,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: '/i2GVEvltEu3BXn5crBSxgKuTaca.jpg',
    id: 614479,
    title: 'Insidious: The Red Door',
    original_language: 'en',
    original_title: 'Insidious: The Red Door',
    overview:
      "To put their demons to rest once and for all, Josh Lambert and a college-aged Dalton Lambert must go deeper into The Further than ever before, facing their family's dark past and a host of new and more horrifying terrors that lurk behind the red door.",
    poster_path: '/d07phJqCx6z5wILDYqkyraorDPi.jpg',
    media_type: 'movie',
    genre_ids: [27, 9648, 53],
    popularity: 929.482,
    release_date: '2023-07-05',
    video: false,
    vote_average: 6.914,
    vote_count: 959,
  },
  {
    adult: false,
    backdrop_path: '/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg',
    id: 667538,
    title: 'Transformers: Rise of the Beasts',
    original_language: 'en',
    original_title: 'Transformers: Rise of the Beasts',
    overview:
      'When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.',
    poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
    media_type: 'movie',
    genre_ids: [28, 12, 878],
    popularity: 1596.732,
    release_date: '2023-06-06',
    video: false,
    vote_average: 7.494,
    vote_count: 2920,
  },
  {
    adult: false,
    backdrop_path: '/f7UI3dYpr7ZUHGo0iIr1Qvy1VPe.jpg',
    id: 1040148,
    title: 'Ruby Gillman, Teenage Kraken',
    original_language: 'en',
    original_title: 'Ruby Gillman, Teenage Kraken',
    overview:
      "Ruby Gillman, a sweet and awkward high school student, discovers she's a direct descendant of the warrior kraken queens. The kraken are sworn to protect the oceans of the world against the vain, power-hungry mermaids. Destined to inherit the throne from her commanding grandmother, Ruby must use her newfound powers to protect those she loves most.",
    poster_path: '/kgrLpJcLBbyhWIkK7fx1fM4iSvf.jpg',
    media_type: 'movie',
    genre_ids: [16, 10751, 14, 35],
    popularity: 560.733,
    release_date: '2023-06-28',
    video: false,
    vote_average: 7.563,
    vote_count: 578,
  },
  {
    adult: false,
    backdrop_path: '/nYDPmxvl0if5vHBBp7pDYGkTFc7.jpg',
    id: 709631,
    title: 'Cobweb',
    original_language: 'en',
    original_title: 'Cobweb',
    overview:
      "Eight year old Peter is plagued by a mysterious, constant tapping from inside his bedroom wall—one that his parents insist is all in his imagination. As Peter's fear intensifies, he believes that his parents could be hiding a terrible, dangerous secret and questions their trust.",
    poster_path: '/cGXFosYUHYjjdKrOmA0bbjvzhKz.jpg',
    media_type: 'movie',
    genre_ids: [27],
    popularity: 1171.645,
    release_date: '2023-07-19',
    video: false,
    vote_average: 6.749,
    vote_count: 195,
  },
  {
    adult: false,
    backdrop_path: '/znUYFf0Sez5lUmxPr3Cby7TVJ6c.jpg',
    id: 447277,
    title: 'The Little Mermaid',
    original_language: 'en',
    original_title: 'The Little Mermaid',
    overview:
      'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
    poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
    media_type: 'movie',
    genre_ids: [12, 10751, 14, 10749],
    popularity: 766.828,
    release_date: '2023-05-18',
    video: false,
    vote_average: 6.548,
    vote_count: 1694,
  },
  {
    adult: false,
    backdrop_path: '/7gFEPIcJDQvGq9xTvlPL2ZQB27c.jpg',
    id: 980489,
    title: 'Gran Turismo',
    original_language: 'en',
    original_title: 'Gran Turismo',
    overview:
      'The ultimate wish fulfillment tale of a teenage Gran Turismo player whose gaming skills won him a series of Nissan competitions to become an actual professional racecar driver.',
    poster_path: '/ckW6FZqMFEKA9DonixjZSAPxJMo.jpg',
    media_type: 'movie',
    genre_ids: [28, 18, 12],
    popularity: 259.048,
    release_date: '2023-08-09',
    video: false,
    vote_average: 7.325,
    vote_count: 137,
  },
];
